# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedState.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eLedState.proto\"\x1f\n\x0fLedStateRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\" \n\rLedStateReply\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\x07Scanner\x12\x30\n\x0cSendLedState\x12\x10.LedStateRequest\x1a\x0e.LedStateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LedState_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LEDSTATEREQUEST']._serialized_start=18
  _globals['_LEDSTATEREQUEST']._serialized_end=49
  _globals['_LEDSTATEREPLY']._serialized_start=51
  _globals['_LEDSTATEREPLY']._serialized_end=83
  _globals['_SCANNER']._serialized_start=85
  _globals['_SCANNER']._serialized_end=144
# @@protoc_insertion_point(module_scope)
