# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedSwitch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fLedSwitch.proto\"$\n\x10LedSwitchRequest\x12\x10\n\x08LedState\x18\x01 \x01(\x08\"!\n\x0eLedSwitchReply\x12\x0f\n\x07message\x18\x01 \x01(\t2?\n\tLedSwitch\x12\x32\n\x0cSendLedState\x12\x11.LedSwitchRequest\x1a\x0f.LedSwitchReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LedSwitch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LEDSWITCHREQUEST']._serialized_start=19
  _globals['_LEDSWITCHREQUEST']._serialized_end=55
  _globals['_LEDSWITCHREPLY']._serialized_start=57
  _globals['_LEDSWITCHREPLY']._serialized_end=90
  _globals['_LEDSWITCH']._serialized_start=92
  _globals['_LEDSWITCH']._serialized_end=155
# @@protoc_insertion_point(module_scope)
