# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import LedSwitch_pb2 as LedSwitch__pb2


class LedSwitchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLedState = channel.unary_unary(
                '/LedSwitch/SendLedState',
                request_serializer=LedSwitch__pb2.LedSwitchRequest.SerializeToString,
                response_deserializer=LedSwitch__pb2.LedSwitchReply.FromString,
                )


class LedSwitchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendLedState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedSwitchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendLedState': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLedState,
                    request_deserializer=LedSwitch__pb2.LedSwitchRequest.FromString,
                    response_serializer=LedSwitch__pb2.LedSwitchReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LedSwitch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LedSwitch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendLedState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LedSwitch/SendLedState',
            LedSwitch__pb2.LedSwitchRequest.SerializeToString,
            LedSwitch__pb2.LedSwitchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
